clutchengineering_api_default_route:
    path: /api/v1
    defaults: { _controller: clutchengineering.api.controller:default }

clutchengineering_api_auth_route:
    path: /api/v1/auth
    defaults: { _controller: clutchengineering.api.controller:auth }

clutchengineering_api_users_route:
    path: /api/v1/users/{user_id}
    defaults: { _controller: clutchengineering.api.controller.users:endpoint, user_id: 0 }