clutchengineering_api_users_route:
    path: /api/v1/users/{user_id}
    defaults: { _controller: clutchengineering.api.controller.users:endpoint, user_id: 0 }
    requirements:
        user_id: \d+
    options:
        middleware: ['clutchengineering.api.auth.api_auth_middleware']

clutchengineering_api_oauth_login:
    path: /oauth/login
    defaults: { _controller: clutchengineering.api.controller.oauth:login }
    methods: [POST]

clutchengineering_api_oauth_authorize:
    path: /oauth/authorize
    defaults: { _controller: clutchengineering.api.controller.oauth:authorize }
    methods: [POST]

clutchengineering_api_oauth_refresh:
    path: /oauth/refresh
    defaults: { _controller: clutchengineering.api.controller.oauth:refresh_token }
    methods: [POST]

clutchengineering_api_oauth_revoke:
    path: /oauth/revoke
    defaults: { _controller: clutchengineering.api.controller.oauth:revoke_token }
    methods: [POST]
    options:
        middleware: ['clutchengineering.api.auth.api_auth_middleware']