# API routes

clutchengineering_api_users_me_route:
    path: /api/v1/users/me
    defaults: { _controller: clutchengineering.api.controller.users:me }
    methods: [GET]

clutchengineering_api_users_user_route:
    path: /api/v1/users/{user_id}
    defaults: { _controller: clutchengineering.api.controller.users:endpoint, user_id: 0 }
    requirements:
        user_id: \d+

# OAuth routes

clutchengineering_api_oauth_login:
    path: /oauth/login
    defaults: { _controller: clutchengineering.api.controller.oauth:login }
    methods: [POST]

clutchengineering_api_oauth_token:
    path: /oauth/token
    defaults: { _controller: clutchengineering.api.controller.oauth:token }
    methods: [POST]

clutchengineering_api_oauth_revoke:
    path: /oauth/revoke
    defaults: { _controller: clutchengineering.api.controller.oauth:revoke_token }
    methods: [POST]