services:
    clutchengineering.api.controller:
        class: clutchengineering\api\controller\core
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'

    clutchengineering.api.controller.users:
        class: clutchengineering\api\controller\users
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'

    clutchengineering.api.admin.controller:
        class: clutchengineering\api\controller\admin_controller
        arguments:
            - '@config'
            - '@template'
            - '@request'
            - '@user'
            - '@language'

    clutchengineering.api.controller.oauth:
        class: clutchengineering\api\controller\oauth
        arguments:
            - '@auth'
            - '@user'
            - '@dbal.conn'
            - '@config'

    clutchengineering.api.listener:
        class: clutchengineering\api\event\listener
        arguments:
            - '@controller.helper'
            - '@template'
        tags:
            - { name: event.listener }

    clutchengineering.api.acp.main:
        class: clutchengineering\api\acp\main_module
        tags:
            - { name: module.acp }
