services:
    danieltj.api.controller:
        class: danieltj\api\controller\core
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'

    danieltj.api.controller.users:
        class: danieltj\api\controller\users
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'

    danieltj.api.listener:
        class: danieltj\api\event\listener
        arguments:
            - '@controller.helper'
            - '@template'
        tags:
            - { name: event.listener }