services:
    clutchengineering.api.controller:
        class: clutchengineering\api\controller\core
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'

    clutchengineering.api.controller.users:
        class: clutchengineering\api\controller\users
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'

    clutchengineering.api.listener:
        class: clutchengineering\api\event\listener
        arguments:
            - '@controller.helper'
            - '@template'
        tags:
            - { name: event.listener }