services:

    # Utilities

    clutchengineering.api.util.date_util:
        class: clutchengineering\api\util\DateUtil

    clutchengineering.api.middleware.rate_limiter:
        class: clutchengineering\api\middleware\RateLimiter
        arguments:
            - 60 # Requests per minute
            - '@cache.driver'

    # Event listeners

    clutchengineering.api.event.api_rate_limit_listener:
        class: clutchengineering\api\event\ApiRateLimitListener
        arguments:
            - '@clutchengineering.api.middleware.rate_limiter'
        tags:
            - { name: kernel.event_subscriber }

    clutchengineering.api.event.api_response_listener:
        class: clutchengineering\api\event\ApiResponseListener
        tags:
            - { name: kernel.event_subscriber }

    # Cron tasks

    clutchengineering.api.cron.task.cleanup_tokens:
        class: clutchengineering\api\cron\task\cleanup_tokens
        arguments:
            - '@clutchengineering.api.auth.token_cleanup'
            - '@config'
        calls:
            - [set_name, [clutchengineering.api.cron.task.cleanup_tokens]]
        tags:
            - { name: cron.task }

    # Controllers

    clutchengineering.api.auth.token_cleanup:
        class: clutchengineering\api\auth\token_cleanup
        arguments:
            - '@dbal.conn'
            - '@config'
            - '%core.table_prefix%'

    clutchengineering.api.controller:
        class: clutchengineering\api\controller\core
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'

    clutchengineering.api.controller.users:
        class: clutchengineering\api\controller\users
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@clutchengineering.api.auth.api_auth_service'

    clutchengineering.api.admin.controller:
        class: clutchengineering\api\controller\admin_controller
        arguments:
            - '@config'
            - '@template'
            - '@request'
            - '@user'
            - '@language'

    clutchengineering.api.auth.token_manager:
        class: clutchengineering\api\auth\token_manager
        arguments:
            - '@dbal.conn'
            - '@config'
            - '%core.table_prefix%'

    clutchengineering.api.auth.api_auth_service:
        class: clutchengineering\api\auth\api_auth_service
        arguments:
            - '@clutchengineering.api.auth.token_manager'

    clutchengineering.api.controller.oauth:
        class: clutchengineering\api\controller\oauth
        arguments:
            - '@auth'
            - '@user'
            - '@dbal.conn'
            - '@config'
            - '@clutchengineering.api.auth.token_manager'
            - '@clutchengineering.api.auth.api_auth_service'

    clutchengineering.api.controller.users:
        class: clutchengineering\api\controller\users
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@clutchengineering.api.auth.api_auth_service'

    # Event listeners
            
    clutchengineering.api.listener:
        class: clutchengineering\api\event\listener
        arguments:
            - '@controller.helper'
            - '@template'
        tags:
            - { name: event.listener }

    # Admin Control Panel

    clutchengineering.api.acp.main:
        class: clutchengineering\api\acp\main_module
        tags:
            - { name: module.acp }
